name: test-home

on:
  push:
    paths:
      - "src/pages/Home.jsx"
      - "src/index.css"
      - "src/App.css"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test-home.yml"
      - ".github/workflows/test-module-template.yml"
  pull_request:
    paths:
      - "src/pages/Home.jsx"
      - "src/index.css"
      - "src/App.css"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test-home.yml"
      - ".github/workflows/test-module-template.yml"

jobs:
  test:
    uses: ./.github/workflows/test-module-template.yml
    with:
      module_name: home
      paths_json: '["src/pages/Home.jsx","src/index.css","src/App.css"]'
