name: test-components

on:
  push:
    paths:
      - "src/components/**"
      - "src/index.css"
      - "src/App.css"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test-components.yml"
      - ".github/workflows/test-module-template.yml"
  pull_request:
    paths:
      - "src/components/**"
      - "src/index.css"
      - "src/App.css"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/test-components.yml"
      - ".github/workflows/test-module-template.yml"

jobs:
  test:
    uses: ./.github/workflows/test-module-template.yml
    with:
      module_name: components
      paths_json: '["src/components/**","src/index.css","src/App.css"]'
